### ISSUE TITLE
Please comment here!

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/furry-octo-chainsaw#1]
Anything will do :smile_cat:

**Comment by swinton** [comment]
:wave: @patrickmckenna

**Comment by githubteacher** [comment]
:tada: @swinton is now a repository collaborator. :balloon:

**Comment by orcunilbeyli** [comment]
Great class! Add me in!

**Comment by BeschtaBrandon** [comment]
Hey Patrick

**Comment by yssong66** [comment]
Hello!

**Comment by githubteacher** [comment]
:tada: @nucro, @BeschtaBrandon, and @yssong66 are now  repository collaborators. :balloon:

**Comment by wielandgmeiner** [comment]
Some comment.

**Comment by bugron** [comment]
@patrickmckenna :+1:

**Comment by githubteacher** [comment]
:tada: @wielandgmeiner and @bugron are now  repository collaborators. :balloon:

**Comment by lite1979** [comment]
Great lecture!

**Comment by githubteacher** [comment]
:tada: @lite1979 is now a repository collaborator. :balloon:

**Comment by neoshops** [comment]
Wohoo.

**Comment by githubteacher** [comment]
:tada: @neoshops is now a repository collaborator. :balloon:

**Comment by sbarnekow** [comment]
Oh hai

**Comment by githubteacher** [comment]
:tada: @sbarnekow is now a repository collaborator. :balloon:

**Comment by realkenlee** [comment]
hello all.

**Comment by githubteacher** [comment]
:tada: @realkenlee is now a repository collaborator. :balloon:
